name: Caching and Artifacts 
on: [workflow_dispatch]

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-cahe-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-npm-cache-
            ${runner.os}-
      - name: Display cache status
        run: echo "${{ toJSON(steps.cache-dependencies.outputs) }}"
      - name: install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: upload code coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-coverage-report
          path: coverage
          retention-days: 5
      - name: Download code coverage report
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: code-coverage-report
      - run: ls -a
      - run: ls -a
        working-directory: code-coverage-report
      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const response = await axios('https://icanhazdadjoke.com/', {
              headers: { 'Accept': 'text/plain' }
            });
            console.log(response.data);